services:
  mc:
    image: itzg/minecraft-server:latest     # multi-arch; works on CAX31
    container_name: cobblemon
    restart: unless-stopped
    ports: ["25565:25565"]                  # still blocked by UFW for now
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      MEMORY: "8G"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      CF_SERVER_MOD: ${SERVER_PACK}
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: "25575"
    volumes:
      - ./mc-data:/data
